name: flutter_colis_app
description: Parcel delivery app demo with Kkiapay and Stripe integration
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  kkiapay_flutter_sdk: ^1.0.0
  stripe_payment: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
